### ISSUE TITLE
cannot enable addon (translations cache for the addon already exists)

### ISSUE THREAD

**Issue by Puupyqueen** [matyalatte/Blender-Uasset-Addon#10]
when I try to enable the addon I get this error

Traceback (most recent call last):
  File "C:\Users\NAME\Downloads\blender-3.4.0-alpha+master.ba74704c9ace-windows.amd64-release\blender-3.4.0-alpha+master.ba74704c9ace-windows.amd64-release\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_uasset_addon\__init__.py", line 42, in register
    translation.register()
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_uasset_addon\translations\translation.py", line 65, in register
    bpy.app.translations.register("blender_uasset_addon", translations_dict)
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'blender_uasset_addon'

I see this and it wont enable

**Comment by matyalatte** [comment]
Can you tell me more details to reproduce the situation?
It looks like you enabled the addon  twice as 2 addons.
For example, I've got the same error when installing the addon twice with a zip file and [my python script](https://github.com/matyalatte/Blender-Uasset-Addon/blob/main/for_dev/regist_without_installing.py).

**Comment by Puupyqueen** [comment]
I first installed "Blender-Uasset-Addon-main" and nothing happened except a blue message at the bottom right corner (it didn't appear in the addon list) then I installed "blender_uasset_addon_v0.2.1" and got the error

**Comment by matyalatte** [comment]
I remember v0.2.1 has an issue about unregister function (fixed at this commit https://github.com/matyalatte/Blender-Uasset-Addon/commit/e562bf11d67eb2b9a2f0dc63d849bf1ea6d70a7a).
It could be the cause.

Can you try a hotfixed version I uploaded here?
https://github.com/matyalatte/Blender-Uasset-Addon/issues/9#issuecomment-1277820118
It's for another issue but includes bugfix for the unregister issue.

If you still get the error, relaunch Blender once.
I think it'll work fine.

**Comment by matyalatte** [comment]
Also, it's not related to the error, but you should remove `C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-Uasset-Addon-main` because Blender will unzip it even if it's not an addon.
There is no problem even if you won't remove the unzipped folder, but it's unnecessary.

**Comment by Puupyqueen** [comment]
Thank you the hotfix worked
