### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by yass03** [matyalatte/Blender-Uasset-Addon#17]
hi, i've installed the addon and tried to open a uasset with no success, i tried differents files, uninstalling the addon, closing blender...

the cmd tab say this

Read prefs: "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\open_urls.py'
Warning: addon-module s4studio found module but without '__addon_enabled__' field, possible name collision from file: 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\s4studio\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\open_urls.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\open_urls.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\open_urls.py'
addon_utils.disable: blender_uasset_addon not disabled
Modules Installed (blender_uasset_addon) from 'C:\\Users\\mimin\\Downloads\\blender_uasset_addon_v0.2.1.zip' into 'C:\\Users\\mimin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
Loading C:\Users\mimin\Downloads\umodel_win32\UmodelSaved\Game\RiggedObjects\Characters\Human\Clothing\Upper_F\Jacket_StuUni03\SK_HUM_F_Upp_StuUni03_Master.uasset...
actual: b'\x02\x00\x00\x00'
expected: b'\xc1\x83*\x9e'
Traceback (most recent call last):
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\import_uasset.py", line 921, in execute
    return self.import_uasset(context)
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\import_uasset.py", line 941, in import_uasset
    _, asset_type = load_uasset(
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\import_uasset.py", line 561, in load_uasset
    asset = Uasset(file, version=ue_version, verbose=verbose)
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\unreal\uasset.py", line 288, in __init__
    self.header = UassetHeader.read(f)
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\unreal\uasset.py", line 56, in read
    io.check(f.read(4), UassetHeader.HEAD)
  File "C:\Users\mimin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_uasset_addon\util\io_util.py", line 45, in check
    raise RuntimeError(msg)
RuntimeError: Parse failed. This is unexpected error.

**Comment by 4rtb** [comment]
Same, I tried this addon in both actual blender versions 3.6 and 4.0, but nothing has changed.

My uasset file: https://www.mediafire.com/file/v9yk873s4qy4gbi/SK_Entity.uasset/file (its from ue 5.2)

**Comment by pilledcarpet123** [comment]
have you figured it out?

**Comment by 4rtb** [comment]
Nope

**Comment by jaylinwylie** [comment]
I have similar errors from various files
```
Python: Traceback (most recent call last):
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/import_uasset.py", line 941, in import_uasset
    _, asset_type = load_uasset(
                    ^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/import_uasset.py", line 561, in load_uasset
    asset = Uasset(file, version=ue_version, verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/unreal/uasset.py", line 288, in __init__
    self.header = UassetHeader.read(f)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/unreal/uasset.py", line 65, in read
    io.check(io.read_int32(f), -1)
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/util/io_util.py", line 45, in check
    raise RuntimeError(msg)
RuntimeError: Parse failed. This is unexpected error.
```

```
Python: Traceback (most recent call last):
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/import_uasset.py", line 941, in import_uasset
    _, asset_type = load_uasset(
                    ^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/import_uasset.py", line 561, in load_uasset
    asset = Uasset(file, version=ue_version, verbose=verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/unreal/uasset.py", line 303, in __init__
    names = [read_names(f, i) for i in range(self.header.name_count)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/unreal/uasset.py", line 303, in <listcomp>
    names = [read_names(f, i) for i in range(self.header.name_count)]
             ^^^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/unreal/uasset.py", line 298, in read_names
    name = io.read_str(f)
           ^^^^^^^^^^^^^^
  File "/home/jaylin/.config/blender/4.5/scripts/addons/blender_uasset_addon/util/io_util.py", line 179, in read_str
    string = file.read((num - 1) * (1 + utf16)).decode(encode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 9: ordinal not in range(128)
```
